version: "3.8"

services:
  database:
    image: "postgres"
    container_name: database
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nest_bd
    volumes:
      - pgdata:/data/postgres

  application:
    build: .
    container_name: application
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
